In [1]:
import pandas as pd

In [2]:

import chardet

with open('data_from_tableau/pool_price_data.csv', 'rb') as f:
    result = chardet.detect(f.read())

print(result['encoding'])

UTF-16

In [3]:
pool_price = pd.read_csv('data_from_tableau/pool_price_data.csv',encoding = 'UTF-16', delimiter='\t')

* `pool_price` is retrieved from [https://public.tableau.com/app/profile/market.analytics/viz/AnnualStatistics_16161854228350/Introduction](https://public.tableau.com/app/profile/market.analytics/viz/AnnualStatistics_16161854228350/Introduction)

* AIL: Alberta Internal Load
* Price: Data on AESO pool price

In [4]:
pool_price.head()

,Date - MST,Date,Hourly Profile,Season,Date (MPT),Date (MST),Calgary,Central,Edmonton,Losses,Northeast,Northwest,South,System Load
0,9/15/2021 9:00:00 AM,9/15/2021,ON PEAK,SUMMER,9/15/2021 10:00:00 AM,9/15/2021 9:00:00 AM,1266.780161,1067.113819,1544.308178,200.283502,1118.404554,759.851224,765.684776,6722.426213
1,9/15/2021 10:00:00 AM,9/15/2021,ON PEAK,SUMMER,9/15/2021 11:00:00 AM,9/15/2021 10:00:00 AM,1287.653290,1069.395994,1535.514516,298.000019,1128.070608,803.054327,757.208444,6878.897198
2,9/15/2021 11:00:00 AM,9/15/2021,ON PEAK,SUMMER,9/15/2021 12:00:00 PM,9/15/2021 11:00:00 AM,1289.471737,1070.229953,1541.107795,250.907487,1117.796138,742.190549,757.621156,6769.324814
3,9/15/2021 12:00:00 PM,9/15/2021,ON PEAK,SUMMER,9/15/2021 1:00:00 PM,9/15/2021 12:00:00 PM,1277.518817,1073.458036,1549.897794,226.553266,1124.194199,720.865027,753.213198,6725.700338
4,9/15/2021 1:00:00 PM,9/15/2021,ON PEAK,SUMMER,9/15/2021 2:00:00 PM,9/15/2021 1:00:00 PM,1257.778953,1059.867696,1548.537893,183.800499,1076.261549,722.194563,746.339415,6594.780569

In [5]:
regional_load = pd.read_csv('data_from_tableau/regonal_load_data.csv',encoding = 'UTF-16', delimiter='\t')

* `regional_load` is retrieved from [https://public.tableau.com/app/profile/market.analytics/viz/AnnualStatistics_16161854228350/Introduction](https://public.tableau.com/app/profile/market.analytics/viz/AnnualStatistics_16161854228350/Introduction)

In [6]:
regional_load.head()

,Date - MST,Hourly Profile1,Season1,Date (MST),AIL,Gas Price,Price,Spark Spread
0,9/15/2021 9:00:00 AM,ON PEAK,SUMMER,9/15/2021 9:00:00 AM,9275,4.55,97.32,63.195
1,9/15/2021 10:00:00 AM,ON PEAK,SUMMER,9/15/2021 10:00:00 AM,9380,4.55,89.37,55.245
2,9/15/2021 11:00:00 AM,ON PEAK,SUMMER,9/15/2021 11:00:00 AM,9314,4.55,104.04,69.915
3,9/15/2021 12:00:00 PM,ON PEAK,SUMMER,9/15/2021 12:00:00 PM,9233,4.55,136.70,102.575
4,9/15/2021 1:00:00 PM,ON PEAK,SUMMER,9/15/2021 1:00:00 PM,9210,4.55,104.76,70.635